M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon Sep 23 14:48:49 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-23T14:48:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1000
%
G90
G05
T1
X7.35Y-4.8972
X7.35Y-5.6497
T2
X5.505Y-2.65
X5.505Y-3.75
X5.6Y-4.05
X5.6Y-4.65
X7.705Y-2.65
X7.705Y-3.75
M30
